
spring.datasource.url=jdbc:mysql://root:AGwHNzjlyZmzxmhJLWmuoCzSYaYSwmPH@shortline.proxy.rlwy.net:12770/gsts
spring.datasource.username=root
spring.datasource.password=AGwHNzjlyZmzxmhJLWmuoCzSYaYSwmPH

# C?u hình DataSource
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# C?u hình Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# C?u hình upload file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.datasource.hikari.connectionTimeout=30000

# C?u hình Cloudinary
cloudinary.cloud_name=dyeje8mx3
cloudinary.api_key=287947198485937
cloudinary.api_secret=A13jl8Bce7B0zlG6mjm2ZG9ElR0

# C?u hình g?i email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tinhevilgenius@gmail.com
spring.mail.password=inoc clug xtbz jnqd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App URL g?c (dùng trong link kích ho?t)
#app.host=https://gstsvn.onrender.com

app.host=http://localhost:8085

company.email = tinhevilgenius@gmail.com
server.port=8085
